---
services:
  commune:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: commune
    shm_size: '4gb' # for the shared memory size
    volumes:
      - ~/.commune:/root/.commune # mount the temporary folder
      - ./:/app # mount the current directory
      - /var/run/docker.sock:/var/run/docker.sock # allow for docker to talk to deamon in outside
    ports:
      - 50050-50250:50050-50250
    restart: unless-stopped